definitions:
  github_com_xiaohangshuhub_xiaohangshu_internal_users_app_features_userapp.CreateCmd:
    properties:
      createby:
        type: string
      email:
        type: string
      loginname:
        type: string
      password:
        type: string
      phone:
        type: string
    type: object
  github_com_xiaohangshuhub_xiaohangshu_internal_users_app_features_userapp.QueryByPassword:
    properties:
      loginname:
        type: string
      password:
        type: string
    type: object
  github_com_xiaohangshuhub_xiaohangshu_internal_users_app_features_userapp.UserDto:
    type: object
  github_com_xiaohangshuhub_xiaohangshu_internal_users_webapi_response.Response-bool:
    properties:
      code:
        type: integer
      data:
        type: boolean
      message:
        type: string
    type: object
  ? github_com_xiaohangshuhub_xiaohangshu_internal_users_webapi_response.Response-github_com_xiaohangshuhub_xiaohangshu_internal_users_app_features_userapp_UserDto
  : properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/github_com_xiaohangshuhub_xiaohangshu_internal_users_app_features_userapp.UserDto'
      message:
        type: string
    type: object
  github_com_xiaohangshuhub_xiaohangshu_internal_users_webapi_response.Response-string:
    properties:
      code:
        type: integer
      data:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/user:
    post:
      consumes:
      - application/json
      description: 创建新用户
      parameters:
      - description: 创建用户参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_xiaohangshuhub_xiaohangshu_internal_users_app_features_userapp.CreateCmd'
      produces:
      - application/json
      responses:
        "200":
          description: 创建成功
          schema:
            $ref: '#/definitions/github_com_xiaohangshuhub_xiaohangshu_internal_users_webapi_response.Response-bool'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/github_com_xiaohangshuhub_xiaohangshu_internal_users_webapi_response.Response-bool'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/github_com_xiaohangshuhub_xiaohangshu_internal_users_webapi_response.Response-bool'
      summary: 创建用户
      tags:
      - User
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: 用户登录验证
      parameters:
      - description: 登录参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_xiaohangshuhub_xiaohangshu_internal_users_app_features_userapp.QueryByPassword'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/github_com_xiaohangshuhub_xiaohangshu_internal_users_webapi_response.Response-github_com_xiaohangshuhub_xiaohangshu_internal_users_app_features_userapp_UserDto'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/github_com_xiaohangshuhub_xiaohangshu_internal_users_webapi_response.Response-github_com_xiaohangshuhub_xiaohangshu_internal_users_app_features_userapp_UserDto'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/github_com_xiaohangshuhub_xiaohangshu_internal_users_webapi_response.Response-github_com_xiaohangshuhub_xiaohangshu_internal_users_app_features_userapp_UserDto'
      summary: 用户登录
      tags:
      - User
  /hello:
    get:
      consumes:
      - application/json
      description: 返回 "hello newb"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_xiaohangshuhub_xiaohangshu_internal_users_webapi_response.Response-string'
      summary: hello Newb
      tags:
      - Hello
swagger: "2.0"
